### ISSUE TITLE
When is the time to open source code?

### ISSUE THREAD

**Issue by Hedlen** [swz30/CycleISP#2]
Hello
I want to reproduce the results of this thesis through the code you provided. I don't know when you will open source. I hope you open source as soon as possible to help my research. Thank you very much.

**Comment by adityac8** [comment]
Hi @Hedlen 
Thank you for your interest in our work. We are in the process of cleaning and documenting the code and would soon release it.
Thanks

**Comment by adityac8** [comment]
The code is available now.
