### ISSUE TITLE
question about the training dataset 

### ISSUE THREAD

**Issue by songjiechong** [swz30/CycleISP#3]
I want to know if you only used raw images to train the RGB2RAW Network Branch and  RAW2RGB Network Branch. For example,  you used clean sRGB images as ground truth for optimizing RAW2RGB network, and I don't know how to get the ground truth.

**Comment by swz30** [comment]
We used the MIT-Adobe Fivek dataset which has RAW images. We process these RAW images using the Libraw library and generate corresponding sRGB images. For more details, see Sec 6.2 of the paper.

**Comment by songjiechong** [comment]
I get it. Thank you very much.
