### ISSUE TITLE
Initial training of CycleISP

### ISSUE THREAD

**Issue by yihu-dev** [swz30/CycleISP#5]
Hi, 
I'm trying to do the initial training on the MIT-Adobe FiveK dataset. The raw image is huge which makes the loader slow. Did you do the cropping online?
Thanks.

**Comment by yihu-dev** [comment]
I did some research and write piece of code based on rawpy to create RAW-RGB pair: [code](https://gist.github.com/yihu-dev/7d68a61ba47fdbcd121a67ec3f2e5446)

There are still some files can not be handled such as mismatched aspect ratio of RAW and processed RGB for some camera type and some flip code are not documented in rawpy. So this code can produce 4952 out of 5000 files.

**Comment by swz30** [comment]
Hi,

- Yes, there was the dimension mismatch issue with some images. Here is a script for converting RAW images to RGB: https://github.com/swz30/CycleISP/blob/master/datasets/convert_fivek_raw2rgb.py

- Next, you can convert both RAW and JPGs into npys (with values in range 0-1) using the following script: https://github.com/swz30/CycleISP/blob/master/datasets/image2npy.py

- yes, we performed online cropping. The images are huge which may make the dataloader slow. Here is a relatively faster dataloader script (Load image, crop, perform bayer unification and augmentation, again crop, and so on.): https://github.com/swz30/CycleISP/blob/master/dataloaders/dataset_rgb2raw.py
