### ISSUE TITLE
Some questions about GPU settings

### ISSUE THREAD

**Issue by Najlepszy** [swz30/CycleISP#9]
Hello, I tried to train the DenoiseNet with my own code on an NVIDIA 1080 Ti GPU, but the GPU memory runs out and I can only train it with size of 64 and batch of 1.  
I would like to know more training details about the GPU settings, such as GPU numbers, etc.

**Comment by swz30** [comment]
Hi @Najlepszy 

The denoising network uses ~3GB memory for a batch size 16 and patch size 256x256. 

Please check your gpu memory (using `nvidia-smi`), maybe it is occupied by some other program.
